# Generated by Django 3.0.5 on 2020-04-29 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_id', models.CharField(choices=[('BAN01', 'Bangade'), ('BUT02', 'Buthai'), ('MAN03', 'Manj'), ('PAM04', 'Pamplet'), ('ARK05', 'Arkoli'), ('KOK06', 'Kokkare')], max_length=5)),
                ('size', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=8)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('Userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
