# Generated by Django 3.0.5 on 2020-04-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fish',
            options={'ordering': ['created_date']},
        ),
    ]
