# Generated by Django 3.0.5 on 2020-04-30 07:47

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200430_1113'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fish',
            managers=[
                ('marine', django.db.models.manager.Manager()),
            ],
        ),
    ]
