# Generated by Django 3.0.5 on 2020-05-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20200430_1317'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fish',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='fish',
            old_name='fish_id',
            new_name='fishid',
        ),
        migrations.AlterField(
            model_name='fish',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], max_length=8),
        ),
    ]
